import '@setaria-ui-plus/components/base/style/css'
import '@setaria-ui-plus/components/input/style/css'
import '@setaria-ui-plus/components/tag/style/css'
import '@setaria-ui-plus/components/option/style/css'
import '@setaria-ui-plus/components/option-group/style/css'
import '@setaria-ui-plus/components/scrollbar/style/css'
import '@setaria-ui-plus/components/popper/style/css'
import '@setaria-ui-plus/theme-chalk/el-select.css'
